spring:
  datasource:
    url: jdbc:mysql://120.79.15.205/lz-codechecker?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 5201314ljc

labsse:
  security:
    validate-code:
      image:
#        length: 6
        expire-seconds: 50
        width: 200
        url: /user:post,/user/*:post;get,/test
    browser:
      login-type: JSON
#      login-page: /demo-login.html
#  security:
#    user:
#      password: 1234
#      name: root